import stylisticJs from "@stylistic/eslint-plugin-js";
import stylisticTs from "@stylistic/eslint-plugin-ts";
import parserTs from "@typescript-eslint/parser";
import type { Linter } from "eslint";

export default {
	plugins: {
		'@stylistic/js': stylisticJs,
		'@stylistic/ts': stylisticTs,
	},
	languageOptions: {
		parser: parserTs,
	},
	rules: {
		"array-callback-return": ["error", { checkForEach: true, allowVoid: true }],
		"constructor-super": "error",
		"for-direction": "error",
		"getter-return": "error",
		"no-async-promise-executor": "error",
		"no-await-in-loop": "off",
		"no-class-assign": "error",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-const-assign": "error",
		"no-constant-binary-expression": "error",
		"no-constant-condition": "warn",
		"no-constructor-return": "error",
		"no-control-regex": "error",
		"no-debugger": "warn",
		"no-dupe-args": "error",
		"no-dupe-class-members": "error",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "error",
		"no-duplicate-case": "error",
		"no-duplicate-imports": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-ex-assign": "error",
		"no-fallthrough": "error",
		"no-func-assign": "error",
		"no-import-assign": "error",
		"no-inner-declarations": "error",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "error",
		"no-obj-calls": "error",
		"no-promise-executor-return": ["error", { allowVoid: true }],
		"no-prototype-builtins": "error",
		"no-self-assign": "error",
		"no-self-compare": "error",
		"no-setter-return": "error",
		"no-sparse-arrays": "error",
		"no-template-curly-in-string": "warn",
		"no-this-before-super": "error",
		"no-undef": "error",
		"no-unexpected-multiline": "error",
		"no-unmodified-loop-condition": "error",
		"no-unreachable": "warn",
		"no-unreachable-loop": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "error",
		"no-unsafe-optional-chaining": "error",
		"no-unused-private-class-members": "warn",
		"no-unused-vars": ["warn", { 
			ignoreRestSiblings: true, 
			destructuredArrayIgnorePattern: "^_",
			argsIgnorePattern: "^_",
			varsIgnorePattern: "^_",
		}],
		"no-use-before-define": "error",
		"no-useless-assignment": "error",
		"no-useless-backreference": "error",
		"require-atomic-updates": "off",
		"use-isnan": "error",
		"valid-typeof": "error",
		"accessor-pairs": "error",
		"arrow-body-style": ["error", "as-needed"],
		"block-scoped-var": "error",
		"camelcase": "error",
		"capitalized-comments": "off",
		"class-methods-use-this": "error",
		"complexity": "off",
		"consistent-return": "off",
		"consistent-this": "off",
		"curly": "error",
		"default-case": "off",
		"default-case-last": "off",
		"default-param-last": "error",
		"dot-notation": "error",
		"eqeqeq": ["error", "always"],
		"func-name-matching": "error",
		"func-names": "off",
		"func-style": ["error", "declaration"],
		"grouped-accessor-pairs": "error",
		"guard-for-in": "off",
		"id-denylist": ["error", "data", "callback", "tmp", "temp", "result", "err", "e"],
		"id-length": "error",
		"id-match": "off",
		"init-declarations": ["error", "always"],
		"logical-assignment-operators": ["error", "always"],
		"max-classes-per-file": "error",
		"max-depth": "off",
		"max-lines": "off",
		"max-lines-per-function": "off",
		"max-nested-callbacks": ["error", 3],
		"max-params": ["error", 4],
		"max-statements": "off",
		"new-cap": ["error", { 
			newIsCap: true,
			capIsNew: true,
			properties: true,
		}],
		"no-alert": "off",
		"no-array-constructor": "error",
		"no-bitwise": "error",
		"no-caller": "error",
		"no-case-declarations": "error",
		"no-console": "warn",
		"no-continue": "off",
		"no-delete-var": "error",
		"no-div-regex": "off",
		"no-else-return": "off",
		"no-empty": "warn",
		"no-empty-function": "warn",
		"no-empty-static-block": "warn",
		"no-eq-null": "error",
		"no-eval": "error",
		"no-extend-native": "off",
		"no-extra-bind": "error",
		"no-extra-boolean-cast": "error",
		"no-extra-label": "error",
		"no-global-assign": "error",
		"no-implicit-coercion": "error",
		"no-implicit-globals": "off",
		"no-implied-eval": "error",
		"no-inline-comments": "off",
		"no-invalid-this": "error",
		"no-iterator": "error",
		"no-label-var": "error",
		"no-labels": "off",
		"no-lone-blocks": "off",
		"no-lonely-if": "error",
		"no-loop-func": "off",
		"no-magic-numbers": "error",
		"no-multi-assign": "error",
		"no-multi-str": "error",
		"no-negated-condition": "off",
		"no-nested-ternary": "error",
		"no-new": "off",
		"no-new-func": "error",
		"no-new-wrappers": "error",
		"no-nonoctal-decimal-escape": "error",
		"no-object-constructor": "error",
		"no-octal": "error",
		"no-octal-escape": "error",
		"no-param-reassign": "error",
		"no-plusplus": "off",
		"no-proto": "error",
		"no-redeclare": "error",
		"no-regex-spaces": "error",
		"no-restricted-exports": "off",
		"no-restricted-globals": "off",
		"no-restricted-imports": "off",
		"no-restricted-properties": "off",
		"no-restricted-syntax": "off",
		"no-return-assign": "error",
		"no-sequences": "error",
		"no-shadow": "error",
		"no-shadow-restricted-names": "error",
		"no-ternary": "off",
		"no-throw-literal": "error",
		"no-undef-init": "off",
		"no-undefined": "off",
		"no-underscore-dangle": "off",
		"no-unneeded-ternary": "error",
		"no-unused-expressions": "error",
		"no-unused-labels": "error",
		"no-useless-call": "error",
		"no-useless-catch": "error",
		"no-useless-computed-key": "error",
		"no-useless-concat": "error",
		"no-useless-constructor": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "error",
		"no-useless-return": "off",
		"no-var": "error",
		"no-void": "off",
		"no-warning-comments": "off",
		"no-with": "error",
		"object-shorthand": "off",
		"one-var": "off",
		"operator-assignment": "off",
		"prefer-arrow-callback": "error",
		"prefer-const": "error",
		"prefer-destructuring": ["error", {
			array: true,
		}],
		"prefer-exponentiation-operator": "off",
		"prefer-named-capture-group": "off",
		"prefer-numeric-literals": "off",
		"prefer-object-has-own": "off",
		"prefer-object-spread": "error",
		"prefer-promise-reject-errors": "error",
		"prefer-regex-literals": "error",
		"prefer-template": "error",
		"radix": "off",
		"require-await": "error",
		"require-unicode-regexp": "off",
		"require-yield": "error",
		"sort-imports": "off",
		"sort-keys": "off",
		"sort-vars": "off",
		"strict": "off",
		"symbol-description": "error",
		"vars-on-top": "off",
		"yoda": "error",

		"@stylistic/js/array-bracket-newline": ["error", {multiline: true}],
		"@stylistic/js/array-bracket-spacing": ["error", "never"],
		"@stylistic/js/array-element-newline": ["error", { 
			consistent: true, 
			multiline: true 
		}],
		"@stylistic/js/arrow-parens": ["error", "always"],
		"@stylistic/js/arrow-spacing": "error",
		"@stylistic/js/block-spacing": "error",
		"@stylistic/js/brace-style": "error",
		"@stylistic/js/comma-dangle": ["error", "always-multiline"],
		"@stylistic/js/comma-spacing": ["error", { 
			before: false, 
			after: true 
		}],
		"@stylistic/js/comma-style": ["error", "last"],
		"@stylistic/js/computed-property-spacing": ["error", "never"],
		"@stylistic/js/dot-location": ["error", "property"],
		"@stylistic/js/eol-last": ["error", "always"],
		"@stylistic/js/function-call-spacing": ["error", "never"],
		"@stylistic/js/function-call-argument-newline": ["error", "consistent"],
		"@stylistic/js/function-paren-newline": ["error", "multiline-arguments"],
		"@stylistic/js/generator-star-spacing": ["error", {
			before: true, 
			after: false
		}],
		"@stylistic/js/implicit-arrow-linebreak": ["error", "beside"],
		"@stylistic/js/indent": ["error", "tab"],
		"@stylistic/js/jsx-quotes": ["error", "prefer-double"],
		"@stylistic/js/key-spacing": ["error", { 
			beforeColon: false, 
			afterColon: true,
		}],
		"@stylistic/js/keyword-spacing": ["error", { before: true }],
		"@stylistic/js/line-comment-position": ["error", { position: "above" }],
		"@stylistic/js/linebreak-style": ["error", "unix"],
		"@stylistic/js/lines-around-comment": ["error", { beforeBlockComment: true }],
		"@stylistic/js/lines-between-class-members": ["error", "always"],
		"@stylistic/js/max-len": ["error", { 
			code: 120,
			ignoreStrings: true,
			ignoreTemplateLiterals: true,
			ignoreRegExpLiterals: true,
		}],
		"@stylistic/js/max-statements-per-line": ["error", { max: 1 }],
		"@stylistic/js/multiline-comment-style": ["error", "starred-block"],
		"@stylistic/js/multiline-ternary": ["error", "always-multiline"],
		"@stylistic/js/new-parens": "error",
		"@stylistic/js/newline-per-chained-call": ["error", { ignoreChainWithDepth: 2 }],
		"@stylistic/js/no-confusing-arrow": "off",
		"@stylistic/js/no-extra-parens": "off",
		"@stylistic/js/no-extra-semi": "error",
		"@stylistic/js/no-floating-decimal": "error",
		"@stylistic/js/no-mixed-operators": "error",
		"@stylistic/js/no-mixed-spaces-and-tabs": "error",
		"@stylistic/js/no-multi-spaces": "error",
		"@stylistic/js/no-multiple-empty-lines": ["error", { max: 1, maxEOF: 1 }],
		"@stylistic/js/no-tabs": ["error", { allowIndentationTabs: true }],
		"@stylistic/js/no-trailing-spaces": "error",
		"@stylistic/js/no-whitespace-before-property": "error",
		"@stylistic/js/nonblock-statement-body-position": ["error", "beside"],
		"@stylistic/js/object-curly-newline": ["error", { consistent: true, multiline: true }],
		"@stylistic/js/object-curly-spacing": ["error", "always"],
		"@stylistic/js/object-property-newline": "error",
		"@stylistic/js/one-var-declaration-per-line": ["error", "always"],
		"@stylistic/js/operator-linebreak": ["error", "before"],
		"@stylistic/js/padded-blocks": ["error", "never"],
		"@stylistic/js/padding-line-between-statements": "off",
		"@stylistic/js/quote-props": ["error", "as-needed"],
		"@stylistic/js/quotes": ["error", "double"],
		"@stylistic/js/rest-spread-spacing": ["error", "never"],
		"@stylistic/js/semi": ["error", "always"],
		"@stylistic/js/semi-spacing": "error",
		"@stylistic/js/semi-style": ["error", "last"],
		"@stylistic/js/space-before-blocks": "error",
		"@stylistic/js/space-before-function-paren": ["error", "never"],
		"@stylistic/js/space-in-parens": ["error", "never"],
		"@stylistic/js/space-infix-ops": "error",
		"@stylistic/js/space-unary-ops": "error",
		"@stylistic/js/spaced-comment": "off",
		"@stylistic/js/switch-colon-spacing": "error",
		"@stylistic/js/template-curly-spacing": "error",
		"@stylistic/js/template-tag-spacing": "error",
		"@stylistic/js/wrap-iife": ["error", "inside"],
		"@stylistic/js/wrap-regex": "off",
		"@stylistic/js/yield-star-spacing": ["error", "before"],

		"@stylistic/ts/block-spacing": "error",
		"@stylistic/ts/brace-style": "error",
		"@stylistic/ts/comma-dangle": ["error", "always-multiline"],
		"@stylistic/ts/comma-spacing": ["error", { 
			before: false, 
			after: true 
		}],
		"@stylistic/ts/function-call-spacing": ["error", "never"],
		"@stylistic/ts/indent": ["error", "tab"],
		"@stylistic/ts/key-spacing": ["error", { 
			beforeColon: false, 
			afterColon: true,
		}],
		"@stylistic/ts/keyword-spacing": ["error", { before: true }],
		"@stylistic/ts/lines-around-comment": ["error", { beforeBlockComment: true }],
		"@stylistic/ts/lines-between-class-members": ["error", "always", { exceptAfterOverload: true }],
		"@stylistic/ts/member-delimiter-style": "error",
		"@stylistic/ts/no-extra-parens": "off",
		"@stylistic/ts/no-extra-semi": "error",
		"@stylistic/ts/object-curly-newline": ["error", { consistent: true, multiline: true }],
		"@stylistic/ts/object-curly-spacing": ["error", "always"],
		"@stylistic/ts/object-property-newline": "error",
		"@stylistic/ts/padding-line-between-statements": "off",
		"@stylistic/ts/quote-props": ["error", "as-needed"],
		"@stylistic/ts/quotes": ["error", "double"],
		"@stylistic/ts/semi": "error",
		"@stylistic/ts/space-before-blocks": "error",
		"@stylistic/ts/space-before-function-paren": ["error", "never"],
		"@stylistic/ts/space-infix-ops": "error",
		"@stylistic/ts/type-annotation-spacing": "error",
	}
} as const satisfies Linter.Config;
