name: publish-beta

on:
  pull_request_target:
    branches:
      - develop
    types: [closed]

jobs:
  publisher:
    name: publisher
    runs-on: ubuntu-latest
    steps:
      - name: check if event is merge
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            exit 1
          fi

      - name: title checker
        uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/check-title.json"
      
      - name: get develop branch
        uses: actions/checkout@v4

      - name: get current version
        uses: duplojs/action-semver@v0.3.0
        id: semver
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: duplojs
          GITHUB_REPO: eslint
          GITHUB_BRANCHE: develop
          REGEXP_PATCH: '^fix'
          REGEXP_MINOR: '^feat'
          REGEXP_MAJOR: '^break'
          OUTPUT_FORMAT: '{MAJOR}.{MINOR}.{PATCH}-beta'

      - name: see version
        run: echo "${{ steps.semver.outputs.COMPUTED_VERSION }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Publish in progress at : `${{ steps.semver.outputs.COMPUTED_VERSION }}`.

      - name: set Version In package.json
        run: |
          sed -i 's/"version":.*".*"/"version": "'${{ steps.semver.outputs.COMPUTED_VERSION }}'"/' package.json

      - name: set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: install dependencies
        run: npm ci

      - name: build
        run: npm run build
      
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published at : `${{ steps.semver.outputs.COMPUTED_VERSION }}`.
